apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.environment }}-{{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.repo }}/{{ .Values.container.name }}:{{ .Values.container.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.container.name }}-config
                  key: greeting
            - name: SECRET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.container.name }}-secrets
                  key: secret_name
