apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.name }}-secrets
type: Opaque
data:
  {{ $phase := .Values.phase }}
  secrets.yaml: {{ .Files.Get (nospace (cat $phase "-secrets.yaml")) | b64enc }}
