apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.name }}-secrets-{{ .Release.Revision }}
type: Opaque
data:
    {{ $environment := .Values.environment }}
    {{ .Values.environment }}-secrets.yaml: {{ .Files.Get (nospace (cat $environment "-secrets.yaml")) | b64enc }}
